parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  App\DataFixtures\:
    resource: '../src/DataFixtures/'
    tags: ['doctrine.fixture.orm']
